### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by mnurisso** [oloapinivad/ECmean4#103]
Details to add to the documentation:

- [x] specify that all the levels are considered when evaluating PIs and that they're regridded with linear interpolation to the obs levels (and also mention which are the ERA5 levels used)
- [x] specify in the models list why for some variables there are less than 12 models
- [x] specify that for each model a single member has been considered as in RK08
- [x] specify that all data are regridded to regular lonlat 1 deg
- [x] mention the 5-sigma variance filter

**Comment by oloapinivad** [comment]
All this is implemented in #111
