### ISSUE TITLE
wfo unit

### ISSUE THREAD

**Issue by oloapinivad** [oloapinivad/ECmean4#11]
This is more related to EC-Earth, but it is a good collateral aspect of using _pint_

```
wfo
kg/m2/s ---> m/100years
Unit converson required...
3.1688087814028946e-06 kilogram / meter ** 3 / second ** 2
Units mismatch, this cannot be handled!
```

What unit is kg/m2/s? perhaps is kg m-2 s-1?

**Comment by jhardenberg** [comment]
Yep: kg divided by square meters, divided by seconds (wfo is the freshwater flux, expressed in mass per unit area per second (basically mm/s for water) )

**Comment by oloapinivad** [comment]
There was a mismatch in the year which was not appreciated. I now use the `century` unit and work perfectly.
