### ISSUE TITLE
Value of the spatial integrals

### ISSUE THREAD

**Issue by oloapinivad** [oloapinivad/ECmean4#15]
Following the introduction of the pint package, a small inconsistency in values of the spatial integrals is observed. I think this is correct as it is treated in #12, but I write it down for the sake of my own clarity. 

Take for example `pr_oce` and `pr_land`. They are measured in Sverdrup, i.e. 10^9 m3/s

Precipitation is provided by the model in kg/m2/s, which, dividing by water density (1000 kg/m3) to get volume means 10^-3 m/s (i.e. 1 mm/s or 86400 mm/day). What we currently do is to integrated in space over the ocean or land surface, mutiplying by the area and the summing ('masked_mean()' function in cdopipe.py), so that we multiply by squared meter and get 10^-3 m3/s. 

It is thus correct to assume that the factor of conversion is 10^-12 (from original units to target units). ERA5 data suggest we have about 17 Sv of precipitation. However, results of 

```
 cdo output -fldsum -mul -timmean -selname,pr BETA_atm_cmip6_1m_1990-1990.nc area.nc 
  1.69177e+10       
```
Which multiplied by 10^-12 does not give the same order of magnitude. 
Indeed, this is taken into account by pint so that we get...

```
| pr_oce       | Precipitation (ocean)          | Sv        |      0.0135796  |     13.4499   | ERA5       | 1990-2019 |
| pme_oce      | Precip. minus evap. (ocean)    | Sv        |     -0.00111626 |     -1.24691  | ERA5       | 1990-2019 |
| pr_land      | Precipitation (land)           | Sv        |      0.00333878 |      3.82094  | ERA5       | 1990-2019 |
| pme_land     | Precip. minus evap. (land)     | Sv        |      0.00100797 |      1.39091  | ERA5       | 1990-2019 |
```

there is a 10^3 factor between older "reference" data and what we currently get. Is this correct? Or was it wrong in the past?

As a further confirmation I found on wiki

> Approximately 505,000 cubic kilometres (121,000 cu mi)[[citation needed](https://en.wikipedia.org/wiki/Wikipedia:Citation_needed)] of water falls as precipitation each year; 398,000 cubic kilometres (95,000 cu mi) of it over the oceans.[[](https://en.wikipedia.org/wiki/Earth_rainfall_climatology#cite_note-chow-2)

398000 km3/year = 398000 * 10^9 m3/year = 0,012 * 10^9 m3/s (Sv), which is in line with what we get from  the new version. 
@jhardenberg could you confirm me that this above is correct, and we need to fix reference values (and perhaps change the unit of reference which is not very handy)?

**Comment by jhardenberg** [comment]
Hmmm... no: 1 Sv = 1 million bathtubs per second ;)  = 1e6 m3/s. Since your original sum is in 10^-3 m3/s, the conversion factor between them is 10^9, not 10^12 ! In fact, using this factor you recover 17 Sv of precipitation. 

As for your wikipedia reference:
flux = 398000 km^3/year = 3.98 10^5 10^9 m^3 / year 
Since one year = 3.156 10^7 sec, 
flux = 3.98 10^14 m^/( 3.156 10^7 sec) = 1,26 10^7  m^3 / s which is 12,7 Sv and again the ballpark of the the 13 Sv suggested by ERA5 ....

**Comment by jhardenberg** [comment]
BTW: 
    ` cdo output -fldsum -mul -timmean -selname,pr BETA_atm_cmip6_1m_1990-1990.nc area.nc`
is coputing precipitation over all the globe, not just the oceans (that is why you get 17 instead of 13 aso specified by ERA)

**Comment by jhardenberg** [comment]
BAsically the problema stems from this line in functions.py:
` units.define('Sv = 1e+9 m^3/s') # Replace Sievert with Sverdrup`
Which should read Sv = 1e+6 m^3/s .... I just committed the change myself to the branch

**Comment by oloapinivad** [comment]
ahaha the sverdrup definition! Everything was self consistent but the definition ahaha :-)
