### ISSUE TITLE
Performance indices should use remapcon

### ISSUE THREAD

**Issue by jhardenberg** [oloapinivad/ECmean4#17]
Currently remapbil is used to perform interpolation of all variables in the performance indices regridding. This is not appropriate for upscaling and something like remapcon should be used. The problem is that the unstructured nemo gri is missing corner data and so does not allow the use of remapcon

**Comment by oloapinivad** [comment]
Branch genbil is currently addressing partially this issue, see also #21

**Comment by oloapinivad** [comment]
This is deprecated since now with xarray+Xesmf we can use only bilinear interpolation. Closing, we might want to reopen this in the future if we go on with the sparse matrix interpolation approach
