### ISSUE TITLE
pattern correlation branch

### ISSUE THREAD

**Issue by oloapinivad** [oloapinivad/ECmean4#23]
I have just introduced a pattern correlation branch https://github.com/oloapinivad/ECmean4/tree/correlation which computes also the correlation for a few selected variables. Currently reference is the PI dataset. Structure is a simplified version of the performance indices script, performing very similar operations. I preferred to keep it separate in order to provide statistics on different diagnostics. 
However, we will need to update our datasets

An example run 

```
(.ECmean4) [ccpd@aa6-100 ECmean4]$ ./correlation_pattern.py BETA 1990 1990
Pattern Correlation for  tas 0.990241
Pattern Correlation for  pr 0.839326
Pattern Correlation for  psl 0.967952
Done in 1.4894 seconds
/ec/res4/scratch/ccpd/ece4/ECmean4/table/CP4_RK08_BETA_1990_1990.txt
```

> | Var   |   Correlation | Domain   | Dataset   |
> |-------+---------------+----------+-----------|
> | tas   |      0.990241 | land     | CRU       |
> | pr    |      0.839326 | global   | CMAP      |
> | psl   |      0.967952 | global   | COADS     |

**Comment by jhardenberg** [comment]
Great!

**Comment by oloapinivad** [comment]
A concern is that a lot of the operatios sare identical. We might to introduce some extra function to share the code

**Comment by jhardenberg** [comment]
How about adding an option to performance_indices so that i can compute pattern correlation, instead of a separate tool?

**Comment by oloapinivad** [comment]
I had thought about that, but the idea behind the tool is that it will work
with a completely different set of variables (if you look at the AR6
document it does not have the same vars of the PI). So it would be more
flexible in this sense to have two different tools, but of course we could
merge the two.


Il giorno mar 12 apr 2022 alle ore 14:14 Jost von Hardenberg <
***@***.***> ha scritto:

**Comment by oloapinivad** [comment]
It will require a specific effort, especially if we want to develop it as it is done in the AR6 (I don't remember the figure). We should need extra variables to be archived in the climatology. This version is quite old, it can be used as starting point but given all the development we did I would assume it as deprecated for now.

**Comment by oloapinivad** [comment]
This is completely deprecated, closing this.
