### ISSUE TITLE
CMIP6 compatibility for synda

### ISSUE THREAD

**Issue by jhardenberg** [oloapinivad/ECmean4#36]
The PR https://github.com/oloapinivad/ECmean4/pull/31 (SPHINX docs) also (I guess by mistake) changed `interfaces/interface_CMIP6.yml`, probably to adapt it to the particular file structure by @oloapinivad  .
The previous version actually was compatible with the directory structure as exposed by synda (available on our machines wilma and mafalda)
In branch [fixcmip6](https://github.com/oloapinivad/ECmean4/tree/fixcmip6) I reintroduce the previous version but I also kept Paolo's version as `interfaces/interface_CMIP6_PD.yml` (so it can be used with `-i CMIP6_PD`). We can have different interface files for different directory structures.

**Comment by oloapinivad** [comment]
Yes, I can confirm it has been included by mistake, thanks for correcting. Should we think about including a test also for cmip6 configuration?

**Comment by jhardenberg** [comment]
Yep...that is indeed an issue... I did not realize that CMIP6 was failing until I tested it ....
