### ISSUE TITLE
CDO pardes has been removed in CDO 2.0.5

### ISSUE THREAD

**Issue by oloapinivad** [oloapinivad/ECmean4#44]
As from the title, this makes the CDO based version no longer operative, since it is used to find which what variables are in the file

**Comment by jhardenberg** [comment]
Has it been substituted by another command?

**Comment by oloapinivad** [comment]
I think that `vardes` should do the same, but we need to check this. Also, on mafalda we still have cdo 1.9.9 which as the `pardes` command, while is no longer there on wilma
