### ISSUE TITLE
lean requirements.txt

### ISSUE THREAD

**Issue by jhardenberg** [oloapinivad/ECmean4#45]
The requirements file currently contains outdated pinned packages and way more than waht is strictly needed. 
A short, lean requirements with only what is needed should be added.

**Comment by jhardenberg** [comment]
I now realize that this issue may be useless if the recommended approach is defining packages in a conda environment.

**Comment by oloapinivad** [comment]
Everything is now based on conda. 
We provide two environemnts, one for running and one for development. Of course, this can be improved.
