### ISSUE TITLE
Installing from PyPI causes dependency errors

### ISSUE THREAD

**Issue by uwefladrich** [oloapinivad/ECmean4#77]
Hi,

When trying to install ECmean4 into a fresh Python virtual environment, I get:
```
> pip install ECmean4

Collecting ECmean4
  Using cached ECmean4-0.1.1-py3-none-any.whl (11.3 MB)
Collecting xarray (from ECmean4)
  Using cached xarray-2023.5.0-py3-none-any.whl (994 kB)
Collecting netcdf4 (from ECmean4)
  Using cached netCDF4-1.6.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.4 MB)
Collecting dask (from ECmean4)
  Using cached dask-2023.6.0-py3-none-any.whl (1.2 MB)
INFO: pip is looking at multiple versions of ecmean4 to determine which version is compatible with other requirements. This could take a while.
Collecting ECmean4
  Using cached ECmean4-0.1.0-py3-none-any.whl (11.3 MB)
ERROR: Cannot install ecmean4==0.1.0 and ecmean4==0.1.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    ecmean4 0.1.1 depends on esmpy
    ecmean4 0.1.0 depends on esmpy

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

Trying to explicitly stating version 0.1.1 does not work either:

```
pip install 'ECmean4==0.1.1'
Collecting ECmean4==0.1.1
  Using cached ECmean4-0.1.1-py3-none-any.whl (11.3 MB)
Collecting xarray (from ECmean4==0.1.1)
  Using cached xarray-2023.5.0-py3-none-any.whl (994 kB)
Collecting netcdf4 (from ECmean4==0.1.1)
  Using cached netCDF4-1.6.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.4 MB)
Collecting dask (from ECmean4==0.1.1)
  Using cached dask-2023.6.0-py3-none-any.whl (1.2 MB)
INFO: pip is looking at multiple versions of ecmean4 to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement esmpy (from ecmean4) (from versions: none)
ERROR: No matching distribution found for esmpy
```

**Comment by uwefladrich** [comment]
What is the `esmpy` package that ECmean4 is looking for? I did not find such a package on PyPI.

**Comment by uwefladrich** [comment]
> What is the `esmpy` package that ECmean4 is looking for? I did not find such a package on PyPI.

Answer to myself: I can see that there is an `esmpy` package on conda-forge, which is meant here.

So I guess that it would work in a conda environment (using `environment.yml`) but not direct installation from PyPI (with `pip install ECmean4`).

**Comment by uwefladrich** [comment]
Okay, installing from conda-forge is fine for me.

In the documentation, the part

> Finally you can install ECmean4 directly from pip
   ``> pip install ECmean4``

can be misunderstood in the way that installation only from PyPI is possible.

**Comment by oloapinivad** [comment]
> In the documentation, the part
> 
> > Finally you can install ECmean4 directly from pip
> > `> pip install ECmean4`
> 
> can be misunderstood in the way that installation only from PyPI is possible.

Fair point, I will update the doc!

**Comment by oloapinivad** [comment]
Hi Uwe, I updated the documentation

https://ecmean4.readthedocs.io/en/latest/installation.html

This should work without the need of downloading the github code
```
> mamba create -n ecmean "python>=3.8" xesmf
> mamba activate ecmean
> pip install ECmean4
```

**Comment by oloapinivad** [comment]
Thanks Uwe, all suggestions considered and - in theory - included! I am closing the issue, please feel free to reopen it if you spot other problems...
